### PR TITLE
Ensure scratch directory exists when calling extractCache

### LINKED ISSUE #23: scratch/buildstamp: No such file or directory
I'm running into this in the post inject step, and I'm not sure how to resolve it:

```
Post job cleanup.
+ : 'Argv0: /home/runner/work/_actions/reproducible-containers/buildkit-cache-dance/v2.1.4/post'
++ dirname /home/runner/work/_actions/reproducible-containers/buildkit-cache-dance/v2.1.4/post
+ dir=/home/runner/work/_actions/reproducible-containers/buildkit-cache-dance/v2.1.4
++ read_action_input skip-extraction
++ /home/runner/work/_actions/reproducible-containers/buildkit-cache-dance/v2.1.4/read-action-input skip-extraction
+ '[' '' == true ']'
+ : 'Prepare Timestamp for Layer Cache Busting'
+ date --iso=ns
++ read_action_input scratch-dir
++ /home/runner/work/_actions/reproducible-containers/buildkit-cache-dance/v2.1.4/read-action-input scratch-dir
+ tee scratch/buildstamp
tee: scratch/buildstamp: No such file or directory
2024-03-16T01:00:08,006374192+00:00
```

### PR DESCRIPTION
**Pull request by Chagui-**
When running the action for the first time and no cache exists, inject does not get called, so scratch dir is not created. Then extracting the cache fails because it tries to write to `scratch/buildstamp` but the scratch folder does not exist.

Workaround is to chance the scrath folder to some other folder that already exists:
```yaml
  - name: inject cache into docker
    uses: reproducible-containers/buildkit-cache-dance@v3
    with:
      ...
      scratch-dir: folder_that_exists_in_the_repo
```

This PR ensures the directory exists even if the inject job is not called. Should fix #23

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Thanks, but CI is failing

**Comment by Chagui-** [comment]
yeah i forgot to build, so i did, then i was missing the signed off so i added it following the instructions (which added a new commit). But the the pipeline was mad because the last commit didn't contain the build.

I reverted and now everything should be contained in a single commit.

**Comment by Chagui-** [comment]
Not sure why its failing now

**Comment by AkihiroSuda** [comment]
Please try this
https://github.com/reproducible-containers/buildkit-cache-dance/blob/5de31fc1534ed8789e63d41ea933c5df9944a261/.github/workflows/unit-tests.yml#L17-L26

**Comment by Chagui-** [comment]
I did try that but it was not updating anything in the dist folder.
I added --no-cache and it seem to have worked.

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Pull request merged**
